"""init schema

Revision ID: 59e8b1031657
Revises:
Create Date: 2025-12-11 08:29:36.913963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59e8b1031657'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookshelves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_basement', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('book_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'name', name='uq_library_bookshelf_name')
    )
    op.create_index(op.f('ix_bookshelves_is_basement'), 'bookshelves', ['is_basement'], unique=False)
    op.create_index(op.f('ix_bookshelves_library_id'), 'bookshelves', ['library_id'], unique=False)
    op.create_table('libraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('basement_bookshelf_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_media_id', sa.UUID(), nullable=True),
    sa.Column('theme_color', sa.String(length=16), nullable=True, comment='Hex color (e.g. #336699) for consistent theming'),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_order', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views_count', sa.BIGINT(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('soft_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['basement_bookshelf_id'], ['bookshelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libraries_archived_at'), 'libraries', ['archived_at'], unique=False)
    op.create_index(op.f('ix_libraries_basement_bookshelf_id'), 'libraries', ['basement_bookshelf_id'], unique=False)
    op.create_index(op.f('ix_libraries_cover_media_id'), 'libraries', ['cover_media_id'], unique=False)
    op.create_index(op.f('ix_libraries_last_activity_at'), 'libraries', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_libraries_soft_deleted_at'), 'libraries', ['soft_deleted_at'], unique=False)
    op.create_index(op.f('ix_libraries_user_id'), 'libraries', ['user_id'], unique=False)
    op.create_foreign_key(
        'fk_bookshelves_library_id_libraries',
        'bookshelves',
        'libraries',
        ['library_id'],
        ['id']
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('trash_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_created_at', 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_deleted_at'), 'media', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_filename'), 'media', ['filename'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_state'), 'media', ['state'], unique=False)
    op.create_index(op.f('ix_media_storage_key'), 'media', ['storage_key'], unique=True)
    op.create_index(op.f('ix_media_trash_at'), 'media', ['trash_at'], unique=False)
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_table('search_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_search_index_entity')
    )
    op.create_index('idx_search_index_entity', 'search_index', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_search_index_type', 'search_index', ['entity_type'], unique=False)
    op.create_index('idx_search_index_updated', 'search_index', ['updated_at'], unique=False)
    op.create_index(op.f('ix_search_index_entity_id'), 'search_index', ['entity_id'], unique=False)
    op.create_index(op.f('ix_search_index_entity_type'), 'search_index', ['entity_type'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon_emoji', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_tag_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_tag_id'], ['tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_name')
    )
    op.create_index('idx_tags_deleted_at', 'tags', ['deleted_at'], unique=False)
    op.create_index('idx_tags_parent_tag_id', 'tags', ['parent_tag_id'], unique=False)
    op.create_index('idx_tags_user_id', 'tags', ['user_id'], unique=False)
    op.create_index(op.f('ix_tags_deleted_at'), 'tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tags_level'), 'tags', ['level'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_parent_tag_id'), 'tags', ['parent_tag_id'], unique=False)
    op.create_index(op.f('ix_tags_usage_count'), 'tags', ['usage_count'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bookshelf_id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('cover_icon', sa.String(length=64), nullable=True, comment='POLICY-BOOK-COVER-ICON-LUCIDE: Optional Lucide icon name'),
    sa.Column('cover_media_id', sa.UUID(), nullable=True, comment='POLICY-BOOK-COVER-MEDIA-STABLE-ONLY: Optional Media UUID for custom covers'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('maturity', sa.String(length=16), nullable=False),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('maturity_score', sa.Integer(), nullable=False),
    sa.Column('legacy_flag', sa.Boolean(), nullable=False),
    sa.Column('manual_maturity_override', sa.Boolean(), nullable=False),
    sa.Column('manual_maturity_reason', sa.Text(), nullable=True),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_count_90d', sa.Integer(), nullable=False),
    sa.Column('previous_bookshelf_id', sa.UUID(), nullable=True, comment='Stores the last active bookshelf before moving to Basement'),
    sa.Column('moved_to_basement_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of latest move into Basement'),
    sa.Column('soft_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookshelf_id'], ['bookshelves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_bookshelf_id'], ['bookshelves.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_bookshelf_id'), 'books', ['bookshelf_id'], unique=False)
    op.create_index(op.f('ix_books_library_id'), 'books', ['library_id'], unique=False)
    op.create_index(op.f('ix_books_moved_to_basement_at'), 'books', ['moved_to_basement_at'], unique=False)
    op.create_index(op.f('ix_books_previous_bookshelf_id'), 'books', ['previous_bookshelf_id'], unique=False)
    op.create_index(op.f('ix_books_soft_deleted_at'), 'books', ['soft_deleted_at'], unique=False)
    op.create_table('media_associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('bookshelf', 'book', 'block', name='entitytypeformedia'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'entity_type', 'entity_id', name='uq_media_associations_media_entity')
    )
    op.create_index('ix_media_associations_entity', 'media_associations', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_media_associations_entity_id'), 'media_associations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_media_associations_media_id'), 'media_associations', ['media_id'], unique=False)
    op.create_table('tag_associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('library', 'bookshelf', 'book', 'block', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id', name='uq_tag_associations_tag_entity')
    )
    op.create_index('ix_tag_associations_entity', 'tag_associations', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_tag_associations_entity_id'), 'tag_associations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tag_associations_tag_id'), 'tag_associations', ['tag_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('soft_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_prev_id', sa.UUID(), nullable=True),
    sa.Column('deleted_next_id', sa.UUID(), nullable=True),
    sa.Column('deleted_section_path', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of soft delete'),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_next_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_prev_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_book_id'), 'blocks', ['book_id'], unique=False)
    op.create_index(op.f('ix_blocks_deleted_at'), 'blocks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blocks_deleted_next_id'), 'blocks', ['deleted_next_id'], unique=False)
    op.create_index(op.f('ix_blocks_deleted_prev_id'), 'blocks', ['deleted_prev_id'], unique=False)
    op.create_index(op.f('ix_blocks_deleted_section_path'), 'blocks', ['deleted_section_path'], unique=False)
    op.create_index(op.f('ix_blocks_soft_deleted_at'), 'blocks', ['soft_deleted_at'], unique=False)
    op.create_table('maturity_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('manual_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maturity_snapshots_book_id'), 'maturity_snapshots', ['book_id'], unique=False)
    op.create_index('ix_maturity_snapshots_book_time', 'maturity_snapshots', ['book_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('chronicle_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicle_events_actor_id'), 'chronicle_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_chronicle_events_block_id'), 'chronicle_events', ['block_id'], unique=False)
    op.create_index(op.f('ix_chronicle_events_book_id'), 'chronicle_events', ['book_id'], unique=False)
    op.create_index('ix_chronicle_events_book_time', 'chronicle_events', ['book_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('ix_chronicle_events_created', 'chronicle_events', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_chronicle_events_event_type'), 'chronicle_events', ['event_type'], unique=False)
    op.create_index('ix_chronicle_events_type_time', 'chronicle_events', ['event_type', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chronicle_events_type_time', table_name='chronicle_events')
    op.drop_index(op.f('ix_chronicle_events_event_type'), table_name='chronicle_events')
    op.drop_index('ix_chronicle_events_created', table_name='chronicle_events')
    op.drop_index('ix_chronicle_events_book_time', table_name='chronicle_events')
    op.drop_index(op.f('ix_chronicle_events_book_id'), table_name='chronicle_events')
    op.drop_index(op.f('ix_chronicle_events_block_id'), table_name='chronicle_events')
    op.drop_index(op.f('ix_chronicle_events_actor_id'), table_name='chronicle_events')
    op.drop_table('chronicle_events')
    op.drop_index('ix_maturity_snapshots_book_time', table_name='maturity_snapshots')
    op.drop_index(op.f('ix_maturity_snapshots_book_id'), table_name='maturity_snapshots')
    op.drop_table('maturity_snapshots')
    op.drop_index(op.f('ix_blocks_soft_deleted_at'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_deleted_section_path'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_deleted_prev_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_deleted_next_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_deleted_at'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_book_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_tag_associations_tag_id'), table_name='tag_associations')
    op.drop_index(op.f('ix_tag_associations_entity_id'), table_name='tag_associations')
    op.drop_index('ix_tag_associations_entity', table_name='tag_associations')
    op.drop_table('tag_associations')
    op.drop_index(op.f('ix_media_associations_media_id'), table_name='media_associations')
    op.drop_index(op.f('ix_media_associations_entity_id'), table_name='media_associations')
    op.drop_index('ix_media_associations_entity', table_name='media_associations')
    op.drop_table('media_associations')
    op.drop_index(op.f('ix_books_soft_deleted_at'), table_name='books')
    op.drop_index(op.f('ix_books_previous_bookshelf_id'), table_name='books')
    op.drop_index(op.f('ix_books_moved_to_basement_at'), table_name='books')
    op.drop_index(op.f('ix_books_library_id'), table_name='books')
    op.drop_index(op.f('ix_books_bookshelf_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_tags_usage_count'), table_name='tags')
    op.drop_index(op.f('ix_tags_parent_tag_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_level'), table_name='tags')
    op.drop_index(op.f('ix_tags_deleted_at'), table_name='tags')
    op.drop_index('idx_tags_user_id', table_name='tags')
    op.drop_index('idx_tags_parent_tag_id', table_name='tags')
    op.drop_index('idx_tags_deleted_at', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_search_index_entity_type'), table_name='search_index')
    op.drop_index(op.f('ix_search_index_entity_id'), table_name='search_index')
    op.drop_index('idx_search_index_updated', table_name='search_index')
    op.drop_index('idx_search_index_type', table_name='search_index')
    op.drop_index('idx_search_index_entity', table_name='search_index')
    op.drop_table('search_index')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_index(op.f('ix_media_trash_at'), table_name='media')
    op.drop_index(op.f('ix_media_storage_key'), table_name='media')
    op.drop_index(op.f('ix_media_state'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_filename'), table_name='media')
    op.drop_index(op.f('ix_media_deleted_at'), table_name='media')
    op.drop_index('ix_media_created_at', table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_libraries_user_id'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_soft_deleted_at'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_last_activity_at'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_cover_media_id'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_basement_bookshelf_id'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_archived_at'), table_name='libraries')
    op.drop_constraint('fk_bookshelves_library_id_libraries', 'bookshelves', type_='foreignkey')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_bookshelves_library_id'), table_name='bookshelves')
    op.drop_index(op.f('ix_bookshelves_is_basement'), table_name='bookshelves')
    op.drop_table('bookshelves')
    # ### end Alembic commands ###
