"""Media Module - File storage with trash lifecycle management

This module provides file storage with trash lifecycle management.
Models are in infra/database/models, repositories in infra/storage/.
"""

# Only export what actually exists in this module
from api.app.modules.media.domain import (
    Media,
    MediaPath,
    MediaType,
    MediaMimeType,
    MediaState,
    EntityTypeForMedia,
    MediaUploaded,
    MediaAssociatedWithEntity,
    MediaDisassociatedFromEntity,
    MediaMovedToTrash,
    MediaRestored,
    MediaPurged,
)

from api.app.modules.media.exceptions import (
    DomainException,
    MediaException,
    MediaNotFoundError,
    InvalidMimeTypeError,
    FileSizeTooLargeError,
    InvalidDimensionsError,
    InvalidDurationError,
    StorageQuotaExceededError,
    MediaInTrashError,
    CannotPurgeError,
    CannotRestoreError,
    AssociationError,
    MediaOperationError,
    MediaRepositoryException,
    MediaRepositoryQueryError,
    MediaRepositorySaveError,
    MediaRepositoryDeleteError,
)

from api.app.modules.media.schemas import (
    UploadMediaRequest,
    UpdateMediaMetadataRequest,
    AssociateMediaRequest,
    DisassociateMediaRequest,
    RestoreMediaRequest,
    BatchRestoreRequest,
    PurgeExpiredMediaRequest,
    MediaResponse,
    MediaListResponse,
    MediaTrashResponse,
    MediaTrashListResponse,
    MediaAssociationResponse,
    EntityMediaListResponse,
    BatchRestoreResponse,
    PurgeExpiredResponse,
    UploadMediaResponse,
    ErrorResponse,
    MediaTypeSchema,
    MediaMimeTypeSchema,
    MediaStateSchema,
    EntityTypeSchema,
)

__all__ = [
    # Domain
    "Media",
    "MediaPath",
    "MediaType",
    "MediaMimeType",
    "MediaState",
    "EntityTypeForMedia",
    "MediaUploaded",
    "MediaAssociatedWithEntity",
    "MediaDisassociatedFromEntity",
    "MediaMovedToTrash",
    "MediaRestored",
    "MediaPurged",
    # Exceptions
    "DomainException",
    "MediaException",
    "MediaNotFoundError",
    "InvalidMimeTypeError",
    "FileSizeTooLargeError",
    "InvalidDimensionsError",
    "InvalidDurationError",
    "StorageQuotaExceededError",
    "MediaInTrashError",
    "CannotPurgeError",
    "CannotRestoreError",
    "AssociationError",
    "MediaOperationError",
    "MediaRepositoryException",
    "MediaRepositoryQueryError",
    "MediaRepositorySaveError",
    "MediaRepositoryDeleteError",
    # Schemas
    "UploadMediaRequest",
    "UpdateMediaMetadataRequest",
    "AssociateMediaRequest",
    "DisassociateMediaRequest",
    "RestoreMediaRequest",
    "BatchRestoreRequest",
    "PurgeExpiredMediaRequest",
    "MediaResponse",
    "MediaListResponse",
    "MediaTrashResponse",
    "MediaTrashListResponse",
    "MediaAssociationResponse",
    "EntityMediaListResponse",
    "BatchRestoreResponse",
    "PurgeExpiredResponse",
    "UploadMediaResponse",
    "ErrorResponse",
    "MediaTypeSchema",
    "MediaMimeTypeSchema",
    "MediaStateSchema",
    "EntityTypeSchema",
]
